FIRE_STATION_CHOICES = {
    "Greater Accra": [
        "Accra City Fire Station",
        "Industrial Area Fire Station",
        "Trade Fair, La Fire Station",
        "Fire Academy & Training School Fire Station",
        "Castle, Osu Fire Station",
        "Flagstaff House Fire Station",
        "Parliament House Fire Station",
        "Ministries Fire Station",
        "Dansoman Fire Station",
        "Regional HQ Korle-Bu Fire Station",
        "Korle-Bu Hospital Fire Station",
        "Weija Fire Station",
        "Nungua Fire Station",
        "Abelenkpe Fire Station",
        "University of Ghana, Legon Fire Station",
        "Madina Fire Station",
        "Adentan Fire Station",
        "Amasaman Fire Station",
        "HQ Sub-Station Fire Station",
        "Adzen Kotoku Fire Station",
        "Tema Regional HQ Fire Station",
        "Tema Industrial Area Fire Station",
        "Ashaiman Fire Station",
        "Prampram Fire Station",
        "Gbetsile Fire Station",
        "Katamanso Fire Station",
        "Dodowa Fire Station",
        "Tema Newtown Fire Station",
        "Devtraco Courts Fire Station",
        "Ada Fire Station",
        "Bost Fire Station"
    ],
    "Western": [
        "Takoradi Regional HQ Fire Station",
        "Apramdu Fire Station",
        "Market Circle Fire Station",
        "Prestea Fire Station",
        "Elubo Fire Station",
        "Nkroful Fire Station",
        "Wassa Akropong Fire Station",
        "Dabiso Fire Station",
        "Atuabo Fire Station",
        "Tarkwa Fire Station",
        "Agona Nkwanta Fire Station",
        "Bibiani Fire Station",
        "Juabuso Fire Station",
        "Daboase Fire Station",
        "Half Assini Fire Station",
        "Enchi Fire Station",
        "Wiawso Fire Station",
        "Asankrangwa Fire Station",
        "Axim Shama Fire Station",
        "Shama Fire Station",
        "Sekondi Metro Fire Station"
    ],
    "Ashanti": [
        "Kumasi Regional HQ Fire Station",
        "Kumasi Metro Fire Station",
        "Manhyia Fire Station",
        "Komfo Anokye Teaching Hospital Fire Station",
        "Breman Fire Station",
        "KNUST Fire Station",
        "Ejisu Fire Station",
        "Bekwai Fire Station",
        "Nkawie Fire Station",
        "Obuasi Fire Station",
        "Effiduasi Fire Station",
        "Fomena Fire Station",
        "Ofinso Fire Station",
        "New Edubiase Fire Station",
        "Mampong Fire Station",
        "Manpongteng Fire Station",
        "Tepa Fire Station",
        "Nyinahin Fire Station",
        "Konongo Fire Station",
        "Ejura Fire Station",
        "Kuntenase Fire Station",
        "Nkenkanso Fire Station",
        "Agona Fire Station"
    ],
    "Eastern": [
        "Koforidua Regional HQ Fire Station",
        "HQ Sub-Station Fire Station",
        "Koforidua Municipal Fire Station",
        "Akwapim Mampong Fire Station",
        "Achiase Fire Station",
        "Nsawam Fire Station",
        "Aduamoa Fire Station",
        "Asesewa Fire Station",
        "New Abirem Fire Station",
        "Akosombo Fire Station",
        "Anyinam Fire Station",
        "Begoro Fire Station",
        "Donkorkrom Fire Station",
        "Kade Fire Station",
        "Akim Oda Fire Station",
        "Peduase Fire Station",
        "Asamankese Fire Station",
        "Ofoase Fire Station",
        "Akwatia Fire Station",
        "Suhum Fire Station",
        "Kibi Fire Station",
        "Nkawkaw Fire Station",
        "Somanya Fire Station",
        "Kpong Fire Station",
        "Mpraeso Fire Station"
    ],
    "Central": [
        "Cape Coast Regional HQ Fire Station",
        "Apam Fire Station",
        "Assin Fosu Fire Station",
        "Agona Nsaba Fire Station",
        "Abura Dunkwa Fire Station",
        "Agona Swedru Fire Station",
        "Budumburam Fire Station",
        "Breman Asikuma Fire Station",
        "Breman Essiam Fire Station",
        "Dunkwa-on-Offin Fire Station",
        "Elmina Fire Station",
        "Komenda Fire Station",
        "Mankesim Fire Station",
        "Cape Coast Metro Fire Station",
        "Twifo Praso Fire Station",
        "University of Cape Coast Fire Station",
        "Winneba Fire Station"
    ],
    "Bono": ["Sunyani Regional HQ Fire Station"],  # existing
    "Bono East": ["Techiman Fire Station"],        # placeholder
    "Ahafo": ["Goaso Fire Station"],               # placeholder
    "Oti": ["Nkwanta Fire Station"],               # placeholder
    "Savannah": ["Damongo Fire Station"],          # placeholder
    "North East": ["Nalerigu Fire Station"],       # placeholder
    "Western North": ["Sefwi Wiawso Fire Station"], # placeholder
    "Volta": [
        "Ho Regional HQ Fire Station",
        "Ho Municipal Fire Station",
        "Adidome Fire Station",
        "Akatsi Fire Station",
        "Anfoega Fire Station",
        "Anloga Fire Station",
        "Denu Fire Station",
        "Hohoe Fire Station",
        "Jasikan Fire Station",
        "Kpandu Fire Station",
        "Kpasa Fire Station",
        "Peki Fire Station",
        "Sogakope Fire Station",
        "Kadjebi Fire Station",
        "Kpetoe Fire Station",
        "Penyi Fire Station",
        "Kete Krachi Fire Station",
        "Chindere Fire Station",
        "Ve-Golokwati Fire Station",
        "Bator Fire Station",
        "Ave Dakpa Fire Station",
        "Dambai Fire Station",
        "Nkwanta Fire Station",
        "Nkonya Fire Station"
    ],
    "Northern": [
        "Tamale Regional HQ Fire Station",
        "HQ Sub-Station Fire Station",
        "Tamale Teaching Hospital Fire Station",
        "Savelugu Fire Station",
        "Salaga Fire Station",
        "Bimbila Fire Station",
        "Walewale Fire Station",
        "Gambaga Fire Station",
        "Buipe Fire Station",
        "Bole Fire Station",
        "Sawla Fire Station",
        "Damongo Fire Station",
        "Sagnarigu Fire Station",
        "Yendi Fire Station",
        "Tamale Metro Fire Station"
    ],
    "Upper East": [
        "Bolga Regional HQ Fire Station",
        "Bolga Municipal Fire Station",
        "Bawku Fire Station",
        "Navrongo Fire Station",
        "Zebila Fire Station",
        "Bongo Fire Station",
        "Sandema Fire Station",
        "Tongo Fire Station",
        "Garu-Timpane Fire Station",
        "Fumbisi Fire Station",
        "Paga Fire Station",
        "Bolga Bost Fire Station",
        "Chiana Fire Station",
        "Zuarungu Fire Station"
    ],
    "Upper West": [
        "Wa Regional HQ Fire Station",
        "Wa Municipal Fire Station",
        "Nadowli Fire Station",
        "Jirapa Fire Station",
        "Lawra Fire Station",
        "Nandom Fire Station",
        "Funsi Fire Station",
        "Lambussie Fire Station",
        "Tumu Fire Station"
    ]
}
