# Generated by Django 5.2.10 on 2026-02-09 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "staffid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "service_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "ghcard",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GREATER_ACC", "Greater Accra"),
                            ("ASHANTI", "Ashanti"),
                            ("WESTERN", "Western"),
                            ("EASTERN", "Eastern"),
                            ("NORTHERN", "Northern"),
                            ("UPPER_EAST", "Upper East"),
                            ("UPPER_WEST", "Upper West"),
                            ("VOLTA", "Volta"),
                            ("BONO", "Bono"),
                            ("BONO_EAST", "Bono East"),
                            ("AHAFO", "Ahafo"),
                            ("Oti", "Oti"),
                            ("SAVANNAH", "Savannah"),
                            ("NORTH_EAST", "North East"),
                            ("WESTERN_NORTH", "Western North"),
                            ("CENTRAL", "Central"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "preferred_qr_method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OFFICER", "Officer"),
                            ("STATION_ADMIN", "Station Admin"),
                            ("REGIONAL_ADMIN", "Regional Admin"),
                            ("SUPERADMIN", "System Super Admin"),
                        ],
                        db_index=True,
                        default="OFFICER",
                        max_length=20,
                    ),
                ),
                ("must_change_password", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staffid", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("station", models.CharField(max_length=150)),
                ("role", models.CharField(default="OFFICER", max_length=50)),
                (
                    "subject",
                    models.CharField(default="General Inquiry", max_length=150),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="contact_messages/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IDRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New ID Request"),
                            ("LOST", "Lost QR"),
                            ("EXPIRED", "Expired ID Renewal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IDRequestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("date_processed", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to="digital_id.idrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfficerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_sent", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="officers/photos/"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("NCO", "Non-Commissioned Officer"),
                            ("CO", "Commissioned Officer"),
                        ],
                        default="NCO",
                        max_length=5,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A Positive", "A Positive"),
                            ("A Negetive", "A Negetive"),
                            ("B Positive", "B Positive"),
                            ("B Negetive", "B Negetive"),
                            ("AB Positive", "AB Positive"),
                            ("AB Negetive", "AB Negetive"),
                            ("O Positive", "O Positive"),
                            ("O Negetive", "O Negetive"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Accra City Fire Station", "Accra City Fire Station"),
                            (
                                "Industrial Area Fire Station",
                                "Industrial Area Fire Station",
                            ),
                            (
                                "Trade Fair, La Fire Station",
                                "Trade Fair, La Fire Station",
                            ),
                            (
                                "Fire Academy & Training School Fire Station",
                                "Fire Academy & Training School Fire Station",
                            ),
                            ("Castle, Osu Fire Station", "Castle, Osu Fire Station"),
                            (
                                "Flagstaff House Fire Station",
                                "Flagstaff House Fire Station",
                            ),
                            (
                                "Parliament House Fire Station",
                                "Parliament House Fire Station",
                            ),
                            ("Ministries Fire Station", "Ministries Fire Station"),
                            ("Dansoman Fire Station", "Dansoman Fire Station"),
                            (
                                "Regional HQ Korle-Bu Fire Station",
                                "Regional HQ Korle-Bu Fire Station",
                            ),
                            (
                                "Korle-Bu Hospital Fire Station",
                                "Korle-Bu Hospital Fire Station",
                            ),
                            ("Weija Fire Station", "Weija Fire Station"),
                            ("Nungua Fire Station", "Nungua Fire Station"),
                            ("Abelenkpe Fire Station", "Abelenkpe Fire Station"),
                            (
                                "University of Ghana, Legon Fire Station",
                                "University of Ghana, Legon Fire Station",
                            ),
                            ("Madina Fire Station", "Madina Fire Station"),
                            ("Adentan Fire Station", "Adentan Fire Station"),
                            ("Amasaman Fire Station", "Amasaman Fire Station"),
                            (
                                "HQ Sub-Station Fire Station",
                                "HQ Sub-Station Fire Station",
                            ),
                            ("Adzen Kotoku Fire Station", "Adzen Kotoku Fire Station"),
                            (
                                "Tema Regional HQ Fire Station",
                                "Tema Regional HQ Fire Station",
                            ),
                            (
                                "Tema Industrial Area Fire Station",
                                "Tema Industrial Area Fire Station",
                            ),
                            ("Ashaiman Fire Station", "Ashaiman Fire Station"),
                            ("Prampram Fire Station", "Prampram Fire Station"),
                            ("Gbetsile Fire Station", "Gbetsile Fire Station"),
                            ("Katamanso Fire Station", "Katamanso Fire Station"),
                            ("Dodowa Fire Station", "Dodowa Fire Station"),
                            ("Tema Newtown Fire Station", "Tema Newtown Fire Station"),
                            (
                                "Devtraco Courts Fire Station",
                                "Devtraco Courts Fire Station",
                            ),
                            ("Ada Fire Station", "Ada Fire Station"),
                            ("Bost Fire Station", "Bost Fire Station"),
                            (
                                "Takoradi Regional HQ Fire Station",
                                "Takoradi Regional HQ Fire Station",
                            ),
                            ("Apramdu Fire Station", "Apramdu Fire Station"),
                            (
                                "Market Circle Fire Station",
                                "Market Circle Fire Station",
                            ),
                            ("Prestea Fire Station", "Prestea Fire Station"),
                            ("Elubo Fire Station", "Elubo Fire Station"),
                            ("Nkroful Fire Station", "Nkroful Fire Station"),
                            (
                                "Wassa Akropong Fire Station",
                                "Wassa Akropong Fire Station",
                            ),
                            ("Dabiso Fire Station", "Dabiso Fire Station"),
                            ("Atuabo Fire Station", "Atuabo Fire Station"),
                            ("Tarkwa Fire Station", "Tarkwa Fire Station"),
                            (
                                "Agona Nkwanta Fire Station",
                                "Agona Nkwanta Fire Station",
                            ),
                            ("Bibiani Fire Station", "Bibiani Fire Station"),
                            ("Juabuso Fire Station", "Juabuso Fire Station"),
                            ("Daboase Fire Station", "Daboase Fire Station"),
                            ("Half Assini Fire Station", "Half Assini Fire Station"),
                            ("Enchi Fire Station", "Enchi Fire Station"),
                            ("Wiawso Fire Station", "Wiawso Fire Station"),
                            ("Asankrangwa Fire Station", "Asankrangwa Fire Station"),
                            ("Axim Shama Fire Station", "Axim Shama Fire Station"),
                            ("Shama Fire Station", "Shama Fire Station"),
                            (
                                "Sekondi Metro Fire Station",
                                "Sekondi Metro Fire Station",
                            ),
                            (
                                "Kumasi Regional HQ Fire Station",
                                "Kumasi Regional HQ Fire Station",
                            ),
                            ("Kumasi Metro Fire Station", "Kumasi Metro Fire Station"),
                            ("Manhyia Fire Station", "Manhyia Fire Station"),
                            (
                                "Komfo Anokye Teaching Hospital Fire Station",
                                "Komfo Anokye Teaching Hospital Fire Station",
                            ),
                            ("Breman Fire Station", "Breman Fire Station"),
                            ("KNUST Fire Station", "KNUST Fire Station"),
                            ("Ejisu Fire Station", "Ejisu Fire Station"),
                            ("Bekwai Fire Station", "Bekwai Fire Station"),
                            ("Nkawie Fire Station", "Nkawie Fire Station"),
                            ("Obuasi Fire Station", "Obuasi Fire Station"),
                            ("Effiduasi Fire Station", "Effiduasi Fire Station"),
                            ("Fomena Fire Station", "Fomena Fire Station"),
                            ("Ofinso Fire Station", "Ofinso Fire Station"),
                            ("New Edubiase Fire Station", "New Edubiase Fire Station"),
                            ("Mampong Fire Station", "Mampong Fire Station"),
                            ("Manpongteng Fire Station", "Manpongteng Fire Station"),
                            ("Tepa Fire Station", "Tepa Fire Station"),
                            ("Nyinahin Fire Station", "Nyinahin Fire Station"),
                            ("Konongo Fire Station", "Konongo Fire Station"),
                            ("Ejura Fire Station", "Ejura Fire Station"),
                            ("Kuntenase Fire Station", "Kuntenase Fire Station"),
                            ("Nkenkanso Fire Station", "Nkenkanso Fire Station"),
                            ("Agona Fire Station", "Agona Fire Station"),
                            (
                                "Koforidua Regional HQ Fire Station",
                                "Koforidua Regional HQ Fire Station",
                            ),
                            (
                                "HQ Sub-Station Fire Station",
                                "HQ Sub-Station Fire Station",
                            ),
                            (
                                "Koforidua Municipal Fire Station",
                                "Koforidua Municipal Fire Station",
                            ),
                            (
                                "Akwapim Mampong Fire Station",
                                "Akwapim Mampong Fire Station",
                            ),
                            ("Achiase Fire Station", "Achiase Fire Station"),
                            ("Nsawam Fire Station", "Nsawam Fire Station"),
                            ("Aduamoa Fire Station", "Aduamoa Fire Station"),
                            ("Asesewa Fire Station", "Asesewa Fire Station"),
                            ("New Abirem Fire Station", "New Abirem Fire Station"),
                            ("Akosombo Fire Station", "Akosombo Fire Station"),
                            ("Anyinam Fire Station", "Anyinam Fire Station"),
                            ("Begoro Fire Station", "Begoro Fire Station"),
                            ("Donkorkrom Fire Station", "Donkorkrom Fire Station"),
                            ("Kade Fire Station", "Kade Fire Station"),
                            ("Akim Oda Fire Station", "Akim Oda Fire Station"),
                            ("Peduase Fire Station", "Peduase Fire Station"),
                            ("Asamankese Fire Station", "Asamankese Fire Station"),
                            ("Ofoase Fire Station", "Ofoase Fire Station"),
                            ("Akwatia Fire Station", "Akwatia Fire Station"),
                            ("Suhum Fire Station", "Suhum Fire Station"),
                            ("Kibi Fire Station", "Kibi Fire Station"),
                            ("Nkawkaw Fire Station", "Nkawkaw Fire Station"),
                            ("Somanya Fire Station", "Somanya Fire Station"),
                            ("Kpong Fire Station", "Kpong Fire Station"),
                            ("Mpraeso Fire Station", "Mpraeso Fire Station"),
                            (
                                "Cape Coast Regional HQ Fire Station",
                                "Cape Coast Regional HQ Fire Station",
                            ),
                            ("Apam Fire Station", "Apam Fire Station"),
                            ("Assin Fosu Fire Station", "Assin Fosu Fire Station"),
                            ("Agona Nsaba Fire Station", "Agona Nsaba Fire Station"),
                            ("Abura Dunkwa Fire Station", "Abura Dunkwa Fire Station"),
                            ("Agona Swedru Fire Station", "Agona Swedru Fire Station"),
                            ("Budumburam Fire Station", "Budumburam Fire Station"),
                            (
                                "Breman Asikuma Fire Station",
                                "Breman Asikuma Fire Station",
                            ),
                            (
                                "Breman Essiam Fire Station",
                                "Breman Essiam Fire Station",
                            ),
                            (
                                "Dunkwa-on-Offin Fire Station",
                                "Dunkwa-on-Offin Fire Station",
                            ),
                            ("Elmina Fire Station", "Elmina Fire Station"),
                            ("Komenda Fire Station", "Komenda Fire Station"),
                            ("Mankesim Fire Station", "Mankesim Fire Station"),
                            (
                                "Cape Coast Metro Fire Station",
                                "Cape Coast Metro Fire Station",
                            ),
                            ("Twifo Praso Fire Station", "Twifo Praso Fire Station"),
                            (
                                "University of Cape Coast Fire Station",
                                "University of Cape Coast Fire Station",
                            ),
                            ("Winneba Fire Station", "Winneba Fire Station"),
                            (
                                "Sunyani Regional HQ Fire Station",
                                "Sunyani Regional HQ Fire Station",
                            ),
                            ("Techiman Fire Station", "Techiman Fire Station"),
                            ("Goaso Fire Station", "Goaso Fire Station"),
                            ("Nkwanta Fire Station", "Nkwanta Fire Station"),
                            ("Damongo Fire Station", "Damongo Fire Station"),
                            ("Nalerigu Fire Station", "Nalerigu Fire Station"),
                            ("Sefwi Wiawso Fire Station", "Sefwi Wiawso Fire Station"),
                            (
                                "Ho Regional HQ Fire Station",
                                "Ho Regional HQ Fire Station",
                            ),
                            ("Ho Municipal Fire Station", "Ho Municipal Fire Station"),
                            ("Adidome Fire Station", "Adidome Fire Station"),
                            ("Akatsi Fire Station", "Akatsi Fire Station"),
                            ("Anfoega Fire Station", "Anfoega Fire Station"),
                            ("Anloga Fire Station", "Anloga Fire Station"),
                            ("Denu Fire Station", "Denu Fire Station"),
                            ("Hohoe Fire Station", "Hohoe Fire Station"),
                            ("Jasikan Fire Station", "Jasikan Fire Station"),
                            ("Kpandu Fire Station", "Kpandu Fire Station"),
                            ("Kpasa Fire Station", "Kpasa Fire Station"),
                            ("Peki Fire Station", "Peki Fire Station"),
                            ("Sogakope Fire Station", "Sogakope Fire Station"),
                            ("Kadjebi Fire Station", "Kadjebi Fire Station"),
                            ("Kpetoe Fire Station", "Kpetoe Fire Station"),
                            ("Penyi Fire Station", "Penyi Fire Station"),
                            ("Kete Krachi Fire Station", "Kete Krachi Fire Station"),
                            ("Chindere Fire Station", "Chindere Fire Station"),
                            ("Ve-Golokwati Fire Station", "Ve-Golokwati Fire Station"),
                            ("Bator Fire Station", "Bator Fire Station"),
                            ("Ave Dakpa Fire Station", "Ave Dakpa Fire Station"),
                            ("Dambai Fire Station", "Dambai Fire Station"),
                            ("Nkonya Fire Station", "Nkonya Fire Station"),
                            (
                                "Tamale Regional HQ Fire Station",
                                "Tamale Regional HQ Fire Station",
                            ),
                            (
                                "Tamale Teaching Hospital Fire Station",
                                "Tamale Teaching Hospital Fire Station",
                            ),
                            ("Savelugu Fire Station", "Savelugu Fire Station"),
                            ("Salaga Fire Station", "Salaga Fire Station"),
                            ("Bimbila Fire Station", "Bimbila Fire Station"),
                            ("Walewale Fire Station", "Walewale Fire Station"),
                            ("Gambaga Fire Station", "Gambaga Fire Station"),
                            ("Buipe Fire Station", "Buipe Fire Station"),
                            ("Bole Fire Station", "Bole Fire Station"),
                            ("Sawla Fire Station", "Sawla Fire Station"),
                            ("Sagnarigu Fire Station", "Sagnarigu Fire Station"),
                            ("Yendi Fire Station", "Yendi Fire Station"),
                            ("Tamale Metro Fire Station", "Tamale Metro Fire Station"),
                            (
                                "Bolga Regional HQ Fire Station",
                                "Bolga Regional HQ Fire Station",
                            ),
                            (
                                "Bolga Municipal Fire Station",
                                "Bolga Municipal Fire Station",
                            ),
                            ("Bawku Fire Station", "Bawku Fire Station"),
                            ("Navrongo Fire Station", "Navrongo Fire Station"),
                            ("Zebila Fire Station", "Zebila Fire Station"),
                            ("Bongo Fire Station", "Bongo Fire Station"),
                            ("Sandema Fire Station", "Sandema Fire Station"),
                            ("Tongo Fire Station", "Tongo Fire Station"),
                            ("Garu-Timpane Fire Station", "Garu-Timpane Fire Station"),
                            ("Fumbisi Fire Station", "Fumbisi Fire Station"),
                            ("Paga Fire Station", "Paga Fire Station"),
                            ("Bolga Bost Fire Station", "Bolga Bost Fire Station"),
                            ("Chiana Fire Station", "Chiana Fire Station"),
                            ("Zuarungu Fire Station", "Zuarungu Fire Station"),
                            (
                                "Wa Regional HQ Fire Station",
                                "Wa Regional HQ Fire Station",
                            ),
                            ("Wa Municipal Fire Station", "Wa Municipal Fire Station"),
                            ("Nadowli Fire Station", "Nadowli Fire Station"),
                            ("Jirapa Fire Station", "Jirapa Fire Station"),
                            ("Lawra Fire Station", "Lawra Fire Station"),
                            ("Nandom Fire Station", "Nandom Fire Station"),
                            ("Funsi Fire Station", "Funsi Fire Station"),
                            ("Lambussie Fire Station", "Lambussie Fire Station"),
                            ("Tumu Fire Station", "Tumu Fire Station"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("AT_POST", "At Post"),
                            ("ON_LEAVE", "On Leave"),
                            ("STUDY_LEAVE", "Study Leave"),
                            ("MATERNITY_LEAVE", "Maternity Leave"),
                            ("SICK_LEAVE", "Sick Leave"),
                            ("TERMINAL_LEAVE", "Terminal Leave"),
                        ],
                        default="AT_POST",
                        max_length=20,
                    ),
                ),
                ("leave_start", models.DateField(blank=True, null=True)),
                ("leave_end", models.DateField(blank=True, null=True)),
                ("called_off", models.BooleanField(default=False)),
                (
                    "qr_token",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="officers/qrcodes/"
                    ),
                ),
                (
                    "service_id_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="officers/service_ids/"
                    ),
                ),
                ("is_active_qr", models.BooleanField(default=False)),
                ("qr_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("date_approved", models.DateTimeField(blank=True, null=True)),
                ("lost_request_pending", models.BooleanField(default=False)),
                ("qr_revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="digital_id.officerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
    ]
