# Generated by Django 5.2.10 on 2026-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_id", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_num",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
