# Generated by Django 6.0 on 2026-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('GREATER_ACC', 'Greater Accra'), ('ASHANTI', 'Ashanti'), ('WESTERN', 'Western'), ('EASTERN', 'Eastern'), ('NORTHERN', 'Northern'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('VOLTA', 'Volta'), ('BONO', 'Bono'), ('BONO_EAST', 'Bono East'), ('AHAFO', 'Ahafo'), ('Oti', 'Oti'), ('SAVANNAH', 'Savannah'), ('NORTH_EAST', 'North East'), ('WESTERN_NORTH', 'Western North'), ('CENTRAL', 'Central')], max_length=20, null=True),
        ),
    ]
