# Generated by Django 5.2.10 on 2026-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_id", "0003_alter_user_phone_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_num",
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact number shown on ID card",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
    ]
