# Generated by Django 6.0 on 2026-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_id', '0003_alter_officerprofile_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='admin_level',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'National Admin'), ('REGIONAL', 'Regional Admin'), ('STATION', 'Station Admin')], db_index=True, max_length=10, null=True),
        ),
    ]
