# Generated by Django 5.2.10 on 2026-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_id", "0004_remove_user_phone_num_user_emergency_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="officerprofile",
            name="front_qr_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="officers/front_qrcodes/"
            ),
        ),
    ]
