# Generated by Django 6.0 on 2026-01-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_id', '0004_officerprofile_admin_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerprofile',
            name='admin_level',
        ),
    ]
