# Generated by Django 6.0 on 2026-01-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_id', '0005_remove_officerprofile_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OFFICER', 'Officer'), ('STATION_ADMIN', 'Station Admin'), ('REGIONAL_ADMIN', 'Regional Admin'), ('SUPERADMIN', 'System Super Admin')], db_index=True, default='OFFICER', max_length=20),
        ),
    ]
