# Generated by Django 5.2.10 on 2026-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_id", "0005_officerprofile_front_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officerprofile",
            name="front_qr_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="officers/front_qrcodes/"
            ),
        ),
    ]
