# Generated by Django 5.2.10 on 2026-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print_id", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printrequest",
            options={"ordering": ["-requested_at"]},
        ),
        migrations.RemoveField(
            model_name="printrequest",
            name="is_printed",
        ),
        migrations.AddField(
            model_name="printrequest",
            name="printed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="printrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PRINTED", "Printed"),
                    ("LOCKED", "Locked"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
